name: Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      
      - name: Test get usuario
        run: mvn test -Dtest=GetUsuarios

      - name: Test post usuario
        run: mvn test -Dtest=PostUsuarios

      - name: Test Delete usuario
        run: mvn test -Dtest=DeleteUsuario

      - name: Test Put usuario
        run: mvn test -Dtest=PutUsuario